language: cpp

env:
  matrix:
    - CMAKE_BUILD_TYPE=DEBUG

install:
- sudo apt-get install libblas-dev
- sudo add-apt-repository ppa:gicmo/packagedump -y
- sudo apt-get update -qq -y
- sudo apt-get install liblapacke-dev
- sudo apt-get install libhdf5-serial-dev
- sudo apt-get install nvidia-cuda-dev nvidia-cuda-toolkit cmake

before_script:
- mkdir -p build
- cd build
- CXX=g++-4.8 cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
- cd ..

script:
- cd build
- make
- cd ..

